### ISSUE TITLE
Meteor 3.0 potential bug 

### ISSUE THREAD

**Issue by harryadel** [Meteor-Community-Packages/meteor-collection2#445]
As reported in Slack by @StorytellerCZ :

```bash

W20240122-18:59:31.199(1)? (STDERR) meteor://💻app/packages/mongo.js:3584
W20240122-18:59:31.200(1)? (STDERR)             throw new Error("".concat(m, " +  is not available on the server. Please use ").concat(getAsyncMethodName(m), "() instead."));
W20240122-18:59:31.200(1)? (STDERR)                   ^
W20240122-18:59:31.200(1)? (STDERR) 
W20240122-18:59:31.200(1)? (STDERR) Error: update +  is not available on the server. Please use updateAsync() instead.
W20240122-18:59:31.200(1)? (STDERR)     at Object.ret.<computed> [as update] (packages/mongo/remote_collection_driver.js:52:15)
W20240122-18:59:31.200(1)? (STDERR)     at Collection.update (packages/mongo/collection.js:959:31)
W20240122-18:59:31.200(1)? (STDERR)     at Collection.Mongo.Collection.<computed> [as update] (packages/aldeed:collection2/main.js:236:23)
W20240122-18:59:31.200(1)? (STDERR)     at packages/accounts-oauth/oauth_server.js:94:41
W20240122-18:59:31.200(1)? (STDERR)     at AsynchronousCursor.forEach (packages/mongo/mongo_driver.js:1115:22)
W20240122-18:59:31.200(1)? (STDERR)     at processTicksAndRejections (node:internal/process/task_queues:95:5)
W20240122-18:59:31.200(1)? (STDERR) 
W20240122-18:59:31.200(1)? (STDERR) Node.js v20.9.0

```

If I add

```js
if (Meteor.isServer && Meteor.isFibersDisabled) {
          return null
        }
```        
to line 236 in `main.js` it goes away. Probably not the best approach though.

**Comment by harryadel** [comment]
Here's the relevant code associated with your problem:
```js
// If async is supported and fibers are disabled
// wait for db operation promise to resolve 
// else just run the sync version as is
if (async && !Meteor.isFibersDisabled) {
        try {
          this[methodName.replace('Async', '')].isCalledFromAsync = true;
          _super.isCalledFromAsync = true;
          return Promise.resolve(_super.apply(this, args)); <---  wait for db operation here
        } catch (err) {
          const addValidationErrorsPropName =
            typeof validationContext.addValidationErrors === 'function'
              ? 'addValidationErrors'
              : 'addInvalidKeys';
          parsingServerError([err], validationContext, addValidationErrorsPropName);
          error = getErrorObject(validationContext, err.message, err.code);
          return Promise.reject(error);
        }
      } else {
        return _super.apply(this, args); <--- run sync version as is
      }
```
With that being said I don't see an problem inherently with an error being thrown out. You're not meant to be using sync DB calls on Meteor 3.0, duh! Moreover, it's in your best interest for an error to be thrown out so you can tell what's DB call failed instead of failing silently. 

I don't see a problem really. Probably the best we can strive for is to beautify the error but IMO the error is informant as is, it doesn't get better than this.
```bash
Error: update +  is not available on the server. Please use updateAsync() instead.
```

**Comment by StorytellerCZ** [comment]
The problem though is that we weren't using any sync call on the server or client. Unless there was something in a package that we couldn't locate.

**Comment by harryadel** [comment]
hmmm, can you produce a replication of this bug? I was going simply by the error message you provided.

**Comment by StorytellerCZ** [comment]
I'm now thinking this could be related to this: https://github.com/meteor/meteor/pull/12978

While the current solution is technically correct, I don't think that it is a best behavior for collection2. I'll look more into this as I work on reproduction.

**Comment by harryadel** [comment]
Ok, keep me posted.

**Comment by jankapunkt** [comment]
@harryadel is this something that needs to be fixed for 3.0 or is this an edge case?
