### ISSUE TITLE
Package crashes server due to "monitor timeout"

### ISSUE THREAD

**Issue by derwaldgeist** [Meteor-Community-Packages/meteor-collection2#461]
I used this package in Meteor 2 for many years, without any issues.

However, when I just returned to my keyboard after a couple of minutes off, I saw this error message in my new Meteor 3 app:

```
W20241111-17:11:43.959(1)? (STDERR) meteor://💻app/packages/aldeed_collection2.js:692
W20241111-17:11:43.959(1)? (STDERR)       const error = new Error(message);
W20241111-17:11:43.959(1)? (STDERR)                     ^
W20241111-17:11:43.960(1)? (STDERR) 
W20241111-17:11:43.960(1)? (STDERR) Error: Failed validation Connection to 127.0.0.1:3051 interrupted due to server monitor timeout
W20241111-17:11:43.960(1)? (STDERR)     at getErrorObject (packages/aldeed:collection2/main.js:572:19)
W20241111-17:11:43.960(1)? (STDERR)     at Collection.Mongo.Collection.<computed> [as updateAsync] (packages/aldeed:collection2/main.js:258:16)
W20241111-17:11:43.960(1)? (STDERR)     at processTicksAndRejections (node:internal/process/task_queues:95:5)
W20241111-17:11:43.960(1)? (STDERR)     at runNextTicks (node:internal/process/task_queues:64:3)
W20241111-17:11:43.979(1)? (STDERR)     at listOnTimeout (node:internal/timers:545:9)
W20241111-17:11:43.979(1)? (STDERR)     at processTimers (node:internal/timers:519:7)
W20241111-17:11:43.979(1)? (STDERR)     at AccountsServer._expireTokens (packages/accounts-base/accounts_server.js:1133:5)
W20241111-17:11:43.979(1)? (STDERR)     at packages/accounts-base/accounts_server.js:1724:4 {
W20241111-17:11:43.979(1)? (STDERR)   invalidKeys: undefined,
W20241111-17:11:43.979(1)? (STDERR)   validationContext: {},
W20241111-17:11:43.979(1)? (STDERR)   code: undefined,
W20241111-17:11:43.979(1)? (STDERR)   sanitizedError: errorClass [Error]: Failed validation Connection to 127.0.0.1:3051 interrupted due to server monitor timeout [400]
W20241111-17:11:43.979(1)? (STDERR)       at getErrorObject (packages/aldeed:collection2/main.js:579:30)
W20241111-17:11:43.983(1)? (STDERR)       at Collection.Mongo.Collection.<computed> [as updateAsync] (packages/aldeed:collection2/main.js:258:16)
W20241111-17:11:43.983(1)? (STDERR)       at processTicksAndRejections (node:internal/process/task_queues:95:5)
W20241111-17:11:43.983(1)? (STDERR)       at runNextTicks (node:internal/process/task_queues:64:3)
W20241111-17:11:43.983(1)? (STDERR)       at listOnTimeout (node:internal/timers:545:9)
W20241111-17:11:43.983(1)? (STDERR)       at processTimers (node:internal/timers:519:7)
W20241111-17:11:43.983(1)? (STDERR)       at AccountsServer._expireTokens (packages/accounts-base/accounts_server.js:1133:5)
W20241111-17:11:43.983(1)? (STDERR)       at packages/accounts-base/accounts_server.js:1724:4 {
W20241111-17:11:43.983(1)? (STDERR)     isClientSafe: true,
W20241111-17:11:43.983(1)? (STDERR)     error: 400,
W20241111-17:11:43.983(1)? (STDERR)     reason: 'Failed validation Connection to 127.0.0.1:3051 interrupted due to server monitor timeout',
W20241111-17:11:43.984(1)? (STDERR)     details: undefined,
W20241111-17:11:43.984(1)? (STDERR)     errorType: 'Meteor.Error'
W20241111-17:11:43.984(1)? (STDERR)   }
W20241111-17:11:43.984(1)? (STDERR) }
W20241111-17:11:43.984(1)? (STDERR) 
W20241111-17:11:43.984(1)? (STDERR) Node.js v20.17.0
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

My server is running on 3050, so I guess it's the connection to Meteor's internal MongoDB that crashed.

I'm on Meteor 3.0.3, the package version is 4.0.3

**Comment by nachocodoner** [comment]
This is reported to the Meteor core, https://github.com/meteor/meteor/issues/13108. I am starting to think if this has to do with something with this package though, since I was not able to reproduce with simple apps. I was not able to see it though with a simple app + collection2.

Do you have any repository that you know that the issue happens what I could do some testing to verify and try to find a constantly way to reproduce this issue for fixing it?

**Comment by jankapunkt** [comment]
@derwaldgeist thanks for reporting, which version is Simple-Schema (Using the npm package or the meteor package of SimpleSchema)?

**Comment by StorytellerCZ** [comment]
Closing in favor of the Meteor issue. Please comment/re-open if there is something specific that we can do here.
