### ISSUE TITLE
Triggers deprecation warnings in Meteor 3.1.1 allow-deny package

### ISSUE THREAD

**Issue by perbergland** [Meteor-Community-Packages/meteor-collection2#462]
Run in a project with Meteor 3 (beta 1) and use the collection.attach method after having enhanced the allow-deny package to include a stack trace.

Result:

```
deny: The "insertAsync" key is deprecated. Use "insert" instead. Error
    at packages/allow-deny/allow-deny.js:557:97
    at Array.forEach (<anonymous>)
    at addValidator (packages/allow-deny/allow-deny.js:549:24)
    at CollectionPrototype.deny (packages/allow-deny/allow-deny.js:72:3)
    at defineDeny (packages/aldeed:collection2/main.js:757:9)
    at Collection.c2AttachSchema [as attachSchema] (packages/aldeed:collection2/main.js:114:5)
```

and

```
deny: The "updateAsync" key is deprecated. Use "update" instead. Error
    at packages/allow-deny/allow-deny.js:557:97
    at Array.forEach (<anonymous>)
    at addValidator (packages/allow-deny/allow-deny.js:549:24)
    at CollectionPrototype.deny (packages/allow-deny/allow-deny.js:72:3)
    at defineDeny (packages/aldeed:collection2/main.js:757:9)
    at Collection.c2AttachSchema [as attachSchema] (packages/aldeed:collection2/main.js:114:5)
```

Unsure what a proper solution is, since the package needs to be compatible with Meteor 3.0 and 3.1 even if 3.1.1 fixes the allow/deny parameters bug.

**Comment by jankapunkt** [comment]
From what I understand the allow-deny does not explicitly use `inserAsync` etc. but just `insert` because they are no MongoDB Collection methods but rather definitions.

The corresponding PRs are in Meteor core and are these:

- https://github.com/meteor/meteor/pull/13522
- https://github.com/meteor/meteor/pull/13499

**Comment by jankapunkt** [comment]
@StorytellerCZ if I get it right we need to move the `*Async`  allow-deny rules back to their normal names but handle them as promises. Would be a new minor release I can provide a PR

**Comment by jankapunkt** [comment]
Please prefer #464

**Comment by derwaldgeist** [comment]
Thanks for the feedback!
