### ISSUE TITLE
meteor-roles and meteor-collection2 setup

### ISSUE THREAD

**Issue by dohomi** [Meteor-Community-Packages/meteor-collection2#70]
Hello Eric,

Maybe its worth adding the config for meteor-role package in https://github.com/aldeed/meteor-collection2#attaching-a-schema-to-a-collection:

```
    "roles.$": {
        type: [String],
        blackbox: true,
        optional: true
    },
```

Cheers,
Dominic

**Comment by evallgar** [comment]
I just read all this post, but I couldnt really understand how it was solved.

This is my code 

```js
createUserWithRole (data) {
    //check data
    // ...
    if(Meteor.isServer){
      newUser = Accounts.createUser({
          email: data.email,
          profile: {
            branch: data.branch,
            branch_id: data.branchId
          }
      });
      if (data.role.length > 0) {
        Roles.addUsersToRoles(newUser, [data.role], Roles.GLOBAL_GROUP );
      }
      Accounts.sendEnrollmentEmail(newUser,data.email);
    }
  }
```
On Accounts.createUser instruction I get the following error:

```unix
Exception while invoking method 'createUserWithRole' Error: Roles must be an object
I20160313-19:19:35.026(-6)?     at getErrorObject (packages/aldeed_collection2/packages/aldeed_collection2.js:371:1)
I20160313-19:19:35.026(-6)?     at [object Object].doValidate (packages/aldeed_collection2/packages/aldeed_collection2.js:354:1)
I20160313-19:19:35.026(-6)?     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2/packages/aldeed_collection2.js:155:1)
I20160313-19:19:35.027(-6)?     at AccountsServer.Ap.insertUserDoc (accounts_server.js:1248:25)
I20160313-19:19:35.033(-6)?     at createUser (password_server.js:980:25)
I20160313-19:19:35.034(-6)?     at AccountsServer.Accounts.createUser (password_server.js:1049:10)
I20160313-19:19:35.034(-6)?     at [object Object].Meteor.methods.createUserWithRole (both/methods/users.js:16:26)
I20160313-19:19:35.034(-6)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160313-19:19:35.035(-6)?     at livedata_server.js:708:19
I20160313-19:19:35.035(-6)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160313-19:19:35.035(-6)? Sanitized and reported to the client as: Roles must be an object [400]
````

This is the Schema:

```js
Schema.User = new SimpleSchema({
    username: { type: String, optional: true },
    emails: { type: Array, optional: true },
    "emails.$": { type: Object },
    "emails.$.address": { type: String, regEx: SimpleSchema.RegEx.Email },
    "emails.$.verified": { type: Boolean, optional: true },
    createdAt: { type: Date, optional: true, defaultValue: moment.utc()._d, autoform: { afFieldInput: { type: "bootstrap-datepicker", "data-date-autoclose": "true" } } },
    profile: { type: Schema.UserProfile, optional: true },
    services: { type: Object, optional: true, blackbox: true },
    roles: { type: Object, optional: true, blackbox: true, defaultValue: 'employee', autoform: { type: "select2", afFieldInput: { } } },
    heartbeat: { type: Date, optional: true, defaultValue: moment.utc()._d } } }
});

Meteor.users.attachSchema(Schema.User);
```

Any help is very much appreciated!!

**Comment by peshi** [comment]
Here's an example of how to set it up

```
    roles: {
        type: Object,
        optional: true,
        blackbox: true,
        autoform: {
            omit: false
        }
    },
    'roles.__global_roles__': {
        type: Array
    },
    'roles.__global_roles__.$': {
        type: String,
        allowedValues: ['admin','user'],
        autoform: {
            afFieldInput: {
                firstOption: "Select a role"
            }
        }
    },
```
