### ISSUE TITLE
Validation error message problems

### ISSUE THREAD

**Issue by zenmatt** [Meteor-Community-Packages/meteor-collection2#89]
See for background: https://github.com/aldeed/meteor-simple-schema/issues/104

I'm having a really weird issue, a problem between Accounts.createUser (via the accounts-entry package) and Collection2.

In local dev mode, for new user signup: I get correct messages ("username already exists", "email already exists") for validation errors, but the SimpleSchema.RegEx.Email regex from the example schema attached to Meteor.users fails with "internal server error", ditto for the username regex.

Even weirder, in production mode (bundled/deployed app) - ALL validation failures yield the internal server error message. 

Some troubleshooting reveals that messages from the isServer block (https://github.com/aldeed/meteor-collection2/blob/master/collection2.js#L437-L443) get passed to the client correctly in dev mode, but not prod(username already exists). However error messages generated client side (https://github.com/aldeed/meteor-collection2/blob/master/collection2.js#L437-L443) yield the "internal server error". I have a ticket open with accounts-entry to see if their Accounts.createUser() call is happening client side or server side (it should be server side). 

Mongo, node and meteor versions are the same in both environments. 

Dev mode errors:

```
I20140717-16:42:16.384(0)? Exception while invoking method 'createUser' Error: failed validation: emails.0.address: Address must be a valid e-mail address
I20140717-16:42:16.390(0)?     at doValidate (packages/collection2/collection2.js:455)
I20140717-16:42:16.398(0)?     at Meteor.Collection.(anonymous function) [as insert] (packages/collection2/collection2.js:269)
I20140717-16:42:16.400(0)?     at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:1021)
I20140717-16:42:16.402(0)?     at createUser (packages/accounts-password/password_server.js:663)
I20140717-16:42:16.403(0)?     at packages/accounts-password/password_server.js:683
I20140717-16:42:16.405(0)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:171)
I20140717-16:42:16.406(0)?     at Object.Accounts._loginMethod (packages/accounts-base/accounts_server.js:287)
I20140717-16:42:16.408(0)?     at Meteor.methods.createUser (packages/accounts-password/password_server.js:669)
I20140717-16:42:16.410(0)?     at methodMap.(anonymous function) (packages/kadira/lib/hijack/wrap_session.js:167)
I20140717-16:42:16.415(0)?     at maybeAuditArgumentChecks (packages/livedata/livedata_server.js:1487)


I20140717-16:51:24.056(0)? Exception while invoking method 'createUser' Error: failed validation: username: Username failed regular expression validation
I20140717-16:51:24.057(0)?     at doValidate (packages/collection2/collection2.js:455)
I20140717-16:51:24.058(0)?     at Meteor.Collection.(anonymous function) [as insert] (packages/collection2/collection2.js:269)
I20140717-16:51:24.060(0)?     at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:1021)
I20140717-16:51:24.064(0)?     at createUser (packages/accounts-password/password_server.js:663)
I20140717-16:51:24.065(0)?     at packages/accounts-password/password_server.js:683
I20140717-16:51:24.067(0)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:171)
I20140717-16:51:24.067(0)?     at Object.Accounts._loginMethod (packages/accounts-base/accounts_server.js:287)
I20140717-16:51:24.068(0)?     at Meteor.methods.createUser (packages/accounts-password/password_server.js:669)
I20140717-16:51:24.068(0)?     at methodMap.(anonymous function) (packages/kadira/lib/hijack/wrap_session.js:167)
I20140717-16:51:24.069(0)?     at maybeAuditArgumentChecks (packages/livedata/livedata_server.js:1487)

```

Prod mode error:

```
Exception while invoking method 'createUser' MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: app.users.$username_1  dup key: { : "matt" }
    at Object.Future.wait (/opt/timelined/app/programs/server/node_modules/fibers/future.js:326:15)
    at null.<anonymous> (packages/meteor/helpers.js:111)
    at MongoConnection.(anonymous function) (packages/mongo-livedata/mongo_driver.js:607)
    at Object.CollectionHooks.defineAdvice.self (packages/collection-hooks/insert.js:39)
    at Object.collection.(anonymous function) [as insert] (packages/collection-hooks/collection-hooks.js:102)
    at Meteor.Collection.(anonymous function) (packages/mongo-livedata/collection.js:476)
    at Meteor.Collection.(anonymous function) [as insert] (packages/collection2/collection2.js:281)
    at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:1021)
    at createUser (packages/accounts-password/password_server.js:663)
    at packages/accounts-password/password_server.js:683

```

Baffled by this and it's really irritating because new user signups get an "internal server error" message instead of the proper validation message.

**Comment by aj07mm** [comment]
I got this problem using Date as a type. 
Here are the following errors: 
```
I20150112-18:12:48.009(-2)? Exception while invoking method 'newClienteTransaction' TypeError: Object 200 has no method 'getUTCMonth'
I20150112-18:12:48.009(-2)?     at Object.dateToDateString (packages/aldeed:simple-schema/simple-schema-utility.js:54)
I20150112-18:12:48.010(-2)?     at SimpleSchema.messageForError (packages/aldeed:simple-schema/simple-schema.js:1051)
I20150112-18:12:48.011(-2)?     at SimpleSchemaValidationContext.simpleSchemaValidationContextKeyErrorMessage [as keyErrorMessage] (packages/aldeed:simple-schema/simple-schema-context.js:191)
I20150112-18:12:48.011(-2)?     at getErrorObject (packages/aldeed:collection2/collection2.js:359)
I20150112-18:12:48.011(-2)?     at doValidate (packages/aldeed:collection2/collection2.js:346)
I20150112-18:12:48.011(-2)?     at Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:147)
I20150112-18:12:48.011(-2)?     at Meteor.methods.newClienteTransaction (app/server/methods.js:21:26)
I20150112-18:12:48.012(-2)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599)
I20150112-18:12:48.012(-2)?     at packages/ddp/livedata_server.js:648
I20150112-18:12:48.012(-2)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
```

**Comment by Siyfion** [comment]
I too am having a similar issue; on my development machine if I provide an invalid email address I get the following exception log:

```
Exception while invoking method 'User.create' Error: Email Address must be a valid e-mail address
     at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
     at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:1017:1)
     at createUser (packages/accounts-password/password_server.js:718:1)
     at Object.Accounts.createUser (packages/accounts-password/password_server.js:776:1)
     at [object Object].Meteor.methods.User.create (app/server/collections/users.js:42:27)
     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:160:1)
     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
     at packages/ddp/livedata_server.js:648:1
Sanitized and reported to the client as: Email Address must be a valid e-mail address [400]
```

And on my production server:

```
Error: Email Address must be a valid e-mail address
    at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
    at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
    at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:1017:1)
    at createUser (packages/accounts-password/password_server.js:718:1)
    at Object.Accounts.createUser (packages/accounts-password/password_server.js:776:1)
    at [object Object].Meteor.methods.User.create (app/server/collections/users.js:42:27)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:160:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
```

On my development environment I get a nice `Meteor.Error` type received by the client, which I parse and display to the user. On the production environment I simply get an "Internal Server Error".

**Comment by aldeed** [comment]
@Siyfion please submit a new issue with a link to a simple reproduction repo. I will investigate. Thanks.

**Comment by Siyfion** [comment]
I really don't think it's required as it won't highlight the issue; **all** you need to do to reproduce this is attach the User schema defined in the README.md of *this* project and then call:

```javascript
Accounts.createUser({
  username: 'TestUsername',
  email: 'anInvalidEmailAddress',
  password: 'test123',
  profile: {
    name: 'Some random name'
  }
});
```

In a production build it will simply throw an `Internal Server Error` rather than the error in debug `Email Address must be a valid e-mail address [400]`.

**Comment by Siyfion** [comment]
@aldeed in fact the same issue occurs with any of the other user fields, for example if you try to create a username with spaces in it ie. "this is not an allowed username" the same thing occurs.

**Comment by aldeed** [comment]
@Siyfion ok, that may be enough to go on, but still create a separate issue. This is a new issue. It seems [this code](https://github.com/meteor/meteor/blob/5535d4cc98840f99b867f0d4132079484b16dbba/packages/ddp-server/livedata_server.js#L1598) isn't being called, but since we do attach a `sanitizedError`, I'll have to figure out what's changing in that flow based on production server.

It's also best if every issue can be linked to a reproduction repo. It helps eliminate the possibility that other packages are to blame by setting up a minimal case with no additional packages.

**Comment by Siyfion** [comment]
@aldeed created #218 to track this issue.
